# Generated by Django 4.2 on 2023-05-09 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='contacto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('numero', models.CharField(max_length=12)),
                ('descripcion', models.TextField(max_length=150)),
                ('region', models.CharField(max_length=50)),
                ('comuna', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('precio', models.IntegerField()),
                ('descripcion', models.TextField()),
                ('stock', models.IntegerField(default=0, null=True)),
                ('oferta', models.CharField(choices=[('0', 'Sin oferta'), ('5', '5% de descuento'), ('10', '10% de descuento'), ('15', '15% de descuento'), ('20', '20% de descuento'), ('25', '25% de descuento'), ('30', '30% de descuento'), ('35', '35% de descuento'), ('40', '40% de descuento'), ('45', '45% de descuento'), ('50', '50% de descuento')], default='0', max_length=2)),
                ('nuevo', models.BooleanField()),
                ('imagen', models.ImageField(blank=True, upload_to='media/%Y/%m/%d')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tienda.categorias')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tienda.marca')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'productos',
                'ordering': ['id'],
            },
        ),
    ]
